if angelsmods and angelsmods.components then
	--SAPHIRITE (IRON, COPPER, QUARTZ, MANGANESE, GOLD, TUNGSTEN)
	data.raw["recipe"]["angelsore1-crushed"].localised_description = {"item-description.angels-ore1-crushed", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore1-chunk"].localised_description = {"item-description.angels-ore1-chunk", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore1-crystal"].localised_description = {"item-description.angels-ore1-crystal", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore1-pure"].localised_description = {"item-description.angels-ore1-pure", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-zinc"}, "", "",}
	--JIVOLITE (IRON, COPPER, TIN, ZINC, RUTILE, PLATINUM)	
	data.raw["recipe"]["angelsore2-crushed"].localised_description = {"item-description.angels-ore2-crushed", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore2-chunk"].localised_description = {"item-description.angels-ore2-chunk", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore2-crystal"].localised_description = {"item-description.angels-ore2-crystal", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore2-pure"].localised_description = {"item-description.angels-ore2-pure", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}, "", "",}
	--STIRATITE (COPPER, IRON, SILVER, BAUXITE, COBALT, CHROME)
	data.raw["recipe"]["angelsore3-crushed"].localised_description = {"item-description.angels-ore3-crushed", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore3-chunk"].localised_description = {"item-description.angels-ore3-chunk", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore3-crystal"].localised_description = {"item-description.angels-ore3-crystal", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore3-pure"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-bauxite"}, "", "",}
	--CROTINIUM (COPPER, IRON, ZINC, LEAD, GOLD, TUNGSTEN)
	data.raw["recipe"]["angelsore4-crushed"].localised_description = {"item-description.angels-ore4-crushed", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore4-chunk"].localised_description = {"item-description.angels-ore4-chunk", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore4-crystal"].localised_description = {"item-description.angels-ore4-crystal", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
	data.raw["recipe"]["angelsore4-pure"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-rutile"}, "", "",}
	--RUBYTE (LEAD, MANGANESE, SILVER, QUARTZ, NICKEL, PLATINUM)
	data.raw["recipe"]["angelsore5-crushed"].localised_description = {"item-description.angels-ore5-crushed", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore5-chunk"].localised_description = {"item-description.angels-ore5-chunk", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore5-crystal"].localised_description = {"item-description.angels-ore5-crystal", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore5-pure"].localised_description = {"item-description.angels-ore5-pure", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}}
	--BOBMONIUM (TIN, QUARTZ, BAUXITE, MANGANESE, RUTILE, CHROME)
	data.raw["recipe"]["angelsore6-crushed"].localised_description = {"item-description.angels-ore6-crushed", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore6-chunk"].localised_description = {"item-description.angels-ore6-chunk", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
    data.raw["recipe"]["angelsore6-crystal"].localised_description = {"item-description.angels-ore6-crystal", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
	data.raw["recipe"]["angelsore6-pure"].localised_description = {"item-description.angels-ore6-pure", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}}

else

	if bobmods and bobmods.plates then
	
		--SAPHIRITE (IRON, COPPER, QUARTZ, NICKEL, RUTILE, ZINC)
		data.raw["recipe"]["angelsore1-crushed"].localised_description = {"item-description.angels-ore1-crushed", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore1-chunk"].localised_description = {"item-description.angels-ore1-chunk", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore1-crystal"].localised_description = {"item-description.angels-ore1-crystal", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore1-pure"].localised_description = {"item-description.angels-ore1-pure", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-zinc"}, "", "",}
		--JIVOLITE (IRON, COPPER, BAUXITE, ZINC, SILVER, TUNGSTEN)
		data.raw["recipe"]["angelsore2-crushed"].localised_description = {"item-description.angels-ore2-crushed", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore2-chunk"].localised_description = {"item-description.angels-ore2-chunk", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore2-crystal"].localised_description = {"item-description.angels-ore2-crystal", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore2-pure"].localised_description = {"item-description.angels-ore2-pure", {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}, "", "",}
		--STIRATITE (COPPER, IRON, COBALT, TIN, RUTILE, BAUXITE)
		data.raw["recipe"]["angelsore3-crushed"].localised_description = {"item-description.angels-ore3-crushed", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore3-chunk"].localised_description = {"item-description.angels-ore3-chunk", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore3-crystal"].localised_description = {"item-description.angels-ore3-crystal", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore3-pure"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-bauxite"}, "", "",}
		--CROTINIUM (COPPER, IRON, LEAD, SILVER, GOLD, RUTILE)
		data.raw["recipe"]["angelsore4-crushed"].localised_description = {"item-description.angels-ore4-crushed", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore4-chunk"].localised_description = {"item-description.angels-ore4-chunk", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore4-crystal"].localised_description = {"item-description.angels-ore4-crystal", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-slag"}, "", "",}
		data.raw["recipe"]["angelsore4-pure"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, {"item-description.loc-dot"}, {"item-description.loc-iron"}, {"item-description.loc-dot"}, {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-silver"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-rutile"}, "", "",}
		--RUBYTE (LEAD, NICKEL, BAUXITE, GOLD, RUTILE, TUNGSTEN)
		data.raw["recipe"]["angelsore5-crushed"].localised_description = {"item-description.angels-ore5-crushed", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore5-chunk"].localised_description = {"item-description.angels-ore5-chunk", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore5-crystal"].localised_description = {"item-description.angels-ore5-crystal", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore5-pure"].localised_description = {"item-description.angels-ore5-pure", {"item-description.loc-lead"}, {"item-description.loc-dot"}, {"item-description.loc-nickel"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-dot"}, {"item-description.loc-gold"}, {"item-description.loc-dot"}, {"item-description.loc-rutile"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}}
		--BOBMONIUM (TIN, QUARTZ, COBALT, ZINC, BAUXITE, TUNGSTEN)
		data.raw["recipe"]["angelsore6-crushed"].localised_description = {"item-description.angels-ore6-crushed", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore6-chunk"].localised_description = {"item-description.angels-ore6-chunk", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore6-crystal"].localised_description = {"item-description.angels-ore6-crystal", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-and"}, {"item-description.loc-slag"}}
		data.raw["recipe"]["angelsore6-pure"].localised_description = {"item-description.angels-ore6-pure", {"item-description.loc-tin"}, {"item-description.loc-dot"}, {"item-description.loc-quartz"}, {"item-description.loc-dot"}, {"item-description.loc-cobalt"}, {"item-description.loc-dot"}, {"item-description.loc-zinc"}, {"item-description.loc-dot"}, {"item-description.loc-bauxite"}, {"item-description.loc-and"}, {"item-description.loc-tungsten"}}
		
		--SINGLE GEM CRYSTALLIZATION
		data.raw["recipe"]["angelsore7-crystallization-1"].localised_name = {"recipe-name.angelsore7-crystallization-1", {"item-name.sapphire-ore"}}
		data.raw["recipe"]["angelsore7-crystallization-2"].localised_name = {"recipe-name.angelsore7-crystallization-2", {"item-name.topaz-ore"}}
		data.raw["recipe"]["angelsore7-crystallization-3"].localised_name = {"recipe-name.angelsore7-crystallization-3", {"item-name.ruby-ore"}}
		data.raw["recipe"]["angelsore7-crystallization-4"].localised_name = {"recipe-name.angelsore7-crystallization-4", {"item-name.emerald-ore"}}
		data.raw["recipe"]["angelsore7-crystallization-5"].localised_name = {"recipe-name.angelsore7-crystallization-5", {"item-name.amethyst-ore"}}
		data.raw["recipe"]["angelsore7-crystallization-6"].localised_name = {"recipe-name.angelsore7-crystallization-6", {"item-name.diamond-ore"}}
	
	else
	
		data.raw["recipe"]["angelsore1-crushed"].localised_description = {"item-description.angels-ore1-crushed", {"item-description.loc-iron"}, "", "", "", ""}
		data.raw["recipe"]["angelsore1-chunk"].localised_description = {"item-description.angels-ore1-chunk", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore1-crystal"].localised_description = {"item-description.angels-ore1-crystal", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore1-pure"].localised_description = {"item-description.angels-ore1-pure", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "", "", "",}	

		data.raw["recipe"]["angelsore2-crushed"].localised_description = {"item-description.angels-ore2-crushed", {"item-description.loc-iron"}, "", "", "", ""}
		data.raw["recipe"]["angelsore2-chunk"].localised_description = {"item-description.angels-ore2-chunk", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore2-crystal"].localised_description = {"item-description.angels-ore2-crystal", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "", "", "",}		
		data.raw["recipe"]["angelsore2-pure"].localised_description = {"item-description.angels-ore2-pure", {"item-description.loc-iron"}, "", "", "", "", "", "", "", "", "", "", "", "",}	

		data.raw["recipe"]["angelsore3-crushed"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, "", "", "", ""}
		data.raw["recipe"]["angelsore3-chunk"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore3-crystal"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore3-pure"].localised_description = {"item-description.angels-ore3-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "", "", "",}	

		data.raw["recipe"]["angelsore4-crushed"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, "", "", "", ""}
		data.raw["recipe"]["angelsore4-chunk"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore4-crystal"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore4-pure"].localised_description = {"item-description.angels-ore4-pure", {"item-description.loc-copper"}, "", "", "", "", "", "", "", "", "", "", "", "",}	

		data.raw["recipe"]["angelsore5-crushed"].localised_description = {"item-description.angels-ore5-pure", "", "", "", "", ""}
		data.raw["recipe"]["angelsore5-chunk"].localised_description = {"item-description.angels-ore5-pure", "", "", "", "", "", "", "", "", ""}	
		data.raw["recipe"]["angelsore5-crystal"].localised_description = {"item-description.angels-ore5-pure", "", "", "", "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore5-pure"].localised_description = {"item-description.angels-ore5-pure", "", "", "", "", "", "", "", "", "", "", "", "", "",}	

		data.raw["recipe"]["angelsore6-crushed"].localised_description = {"item-description.angels-ore6-pure", "", "", "", "", ""}
		data.raw["recipe"]["angelsore6-chunk"].localised_description = {"item-description.angels-ore6-pure", "", "", "", "", "", "", "", "", ""}	
		data.raw["recipe"]["angelsore6-crystal"].localised_description = {"item-description.angels-ore6-pure", "", "", "", "", "", "", "", "", "", "", "", "", "",}	
		data.raw["recipe"]["angelsore6-pure"].localised_description = {"item-description.angels-ore6-pure", "", "", "", "", "", "", "", "", "", "", "", "", "",}
	end
end